# Generated by Django 5.1.7 on 2025-10-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lichsu', '0002_initial'),
    ]

    operations = [
    ]
