# Generated by Django 5.1.7 on 2025-10-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phantichanh', '0001_initial'),
    ]

    operations = [
    ]
